owner      = "rimbaudcode"
fullName   = "art rimbaud"
email      = "rimbaudcode[at]gmail(DoT)com"
license    = "BSD3"
cabal      = false
lib        = true
executable = true
test       = true
benchmark  = true
github     = true
travis     = true

ghcVersions = ["8.0.2", "8.2.2", "8.4.4"]
stylish.url = "https://raw.githubusercontent.com/kowainik/org/master/.stylish-haskell.yaml"

extensions = [ "ConstraintKinds"
             , "DeriveGeneric"
             , "GeneralizedNewtypeDeriving"
             , "InstanceSigs"
             , "KindSignatures"
             , "LambdaCase"
             , "OverloadedStrings"
             , "RecordWildCards"
             , "ScopedTypeVariables"
             , "StandaloneDeriving"
             , "TupleSections"
             , "TypeApplications"
             , "ViewPatterns"
             ]

[prelude]
    package = "relude"
    module  = "Relude"
